const results = [
    {   id: 1,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r1.jpg",
    },
    {   id: 2,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r2.jpg",
    },
    {   id: 3,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r3.jpg",
    },
    {   id: 4,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r4.jpg",
    },
    {   id: 5,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r5.jpg",
    },
    {   id: 6,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r6.jpg",
    },
    {   id: 7,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r7.jpg",
    },
    {   id: 8,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r8.jpg",
    },
    {   id: 9,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r9.jpg",
    },
    {   id: 10,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r10.jpg",
    },
    {   id: 11,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r11.jpg",
    },
    {   id: 12,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r12.jpg",
    },
    {   id: 13,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r13.jpg",
    },
    {   id: 14,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r14.jpg",
    },
    {   id: 15,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r15.jpg",
    },
    {   id: 16,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r16.jpg",
    },
    {   id: 17,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r17.jpg",
    },
    {   id: 18,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r18.jpg",
    },
    {   id: 19,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r19.jpg",
    },
    {   id: 20,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r20.jpg",
    },
    {   id: 21,
        image: "https://raw.githubusercontent.com/addleonel/ghcenter/main/homewc/src/assets/static/results/r21.jpg",
    },
]


export {
    results, 
};